# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodname', models.CharField(max_length=50)),
                ('goodprice', models.FloatField()),
                ('goodcount', models.IntegerField()),
                ('goodimg', models.FileField(upload_to='goods/')),
                ('gooddesc', models.TextField()),
                ('gooddate', models.DateTimeField(auto_now_add=True)),
                ('goodstatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=50)),
                ('childcount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=50)),
                ('typeimg', models.FileField(upload_to='types/')),
                ('typedate', models.DateTimeField(auto_now_add=True)),
                ('childcount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphone', models.CharField(max_length=50)),
                ('useraddress', models.CharField(max_length=250)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('userreguin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Place')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='goodtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Types'),
        ),
    ]
