# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('message', models.CharField(max_length=250)),
                ('token', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('epic', models.CharField(max_length=50)),
                ('ephone', models.CharField(max_length=50)),
                ('edate', models.CharField(max_length=250)),
                ('estatus', models.IntegerField()),
                ('ecount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userpass',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
