# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170909_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=50)),
                ('serviceprice', models.FloatField()),
                ('servicecount', models.IntegerField()),
                ('servicedate', models.DateTimeField(auto_now_add=True)),
                ('servicestatus', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='echo',
            name='uaddress',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='echo',
            name='uplease',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
