# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='pricetype',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
